name: Deploy Zola Site to GitHub Pages

on:
  push:
    branches: ["main"]
  schedule:
    # 毎週日曜日の午前9時に実行（UTC）- RSS更新用
    - cron: '0 9 * * 0'
  workflow_dispatch:

# 権限設定
permissions:
  contents: read
  pages: write
  id-token: write

# 並行実行を停止
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ZOLA_VERSION: 0.18.0
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install and setup Zola
      run: |
        wget -O zola.tar.gz https://github.com/getzola/zola/releases/latest/download/zola-x86_64-unknown-linux-gnu.tar.gz
        tar -xzf zola.tar.gz
        sudo mv zola /usr/local/bin/

    - name: Fetch Zenn RSS and build
      run: |
        node scripts/fetch-zenn-rss.js
        zola build

    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './public'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

