name: Deploy Static Site to GitHub Pages

on:
  schedule:
    # 毎週日曜日の午前9時に実行（UTC）- RSS更新用
    - cron: '0 9 * * 0'
  workflow_dispatch:

# 権限設定
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  update-rss:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Setup Zola
      run: |
        wget -O zola.tar.gz https://github.com/getzola/zola/releases/latest/download/zola-x86_64-unknown-linux-gnu.tar.gz
        tar -xzf zola.tar.gz
        sudo mv zola /usr/local/bin/

    - name: Fetch Zenn RSS and rebuild
      run: |
        node scripts/fetch-zenn-rss.js
        zola build

    - name: Commit updated site
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add public/ content/zenn/
        git diff --staged --quiet || git commit -m "Auto-update: Fetch latest Zenn articles"
        git push

